// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erovyuxyxtqyoowmdmdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyb3Z5dXh5eHRxeW9vd21kbWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjU5NjcsImV4cCI6MjA2NDUwMTk2N30.ehhoPGyokqISyQPVjpVFOjMCK3TGdS5ZCjnDeT-1BwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);